version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq  
    restart: always
    env_file:
      .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" # JMS Port
      - "15672:15672" # Management Port - default user:pass = guest:guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  backend:
    depends_on:
      - mariadb
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    env_file:
      .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - ./:/backend
      - ~/.m2:/root/.m2

volumes:
  db:
  rabbitmq_data:
