version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql


  backend:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    env_file:
      .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - ./:/backend
      - ~/.m2:/root/.m2

volumes:
  db:
