version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mariadb
    image: alhassanraad/unility:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ~/.m2:/root/.m2

volumes:
  db:
