version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./secrets.env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    env_file:
      - ./secrets.env
    ports:
      - "5672:5672" # JMS Port
      - "15672:15672" # Management Port - default user:pass = guest:guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    depends_on:
      - mariadb
      - rabbitmq
    image: alhassanraad/unility:latest
    restart: on-failure
    env_file:
      - ./secrets.env
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ~/.m2:/root/.m2

volumes:
  db:
  rabbitmq_data: