version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./secrets.env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mariadb
    image: alhassanraad/unility:latest
    restart: on-failure
    env_file:
      - ./secrets.env
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ~/.m2:/root/.m2

volumes:
  db: