name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            alhassanraad/unility:${{ github.sha }}
            alhassanraad/unility:latest


  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    name: Deploy to Server
    steps:

      - name: Export secrets to env file
        run: |
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> /home/alhassanraad15/backend/secrets.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> /home/alhassanraad15/backend/secrets.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /home/alhassanraad15/backend/secrets.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /home/alhassanraad15/backend/secrets.env


      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/backend
            git fetch
            git pull
            sudo docker-compose -f docker-compose-prod.yml pull
            sudo docker-compose -f docker-compose-prod.yml up -d --no-deps --build backend
            docker ps -a
